if(HAVE_CXX_EMBED)
    set(XBB_ASSET_ENCODE_ARGS "--embed")
    set(_xbb_asset_mode "embed")
else()
    set(XBB_ASSET_ENCODE_ARGS "")
    set(_xbb_asset_mode "header")
endif()

set(XBB_ASSET_MODE_STAMP "${CMAKE_BINARY_DIR}/assets/asset_mode.stamp")
set(_xbb_prev_asset_mode "")
if(EXISTS "${XBB_ASSET_MODE_STAMP}")
    file(READ "${XBB_ASSET_MODE_STAMP}" _xbb_prev_asset_mode)
endif()
if(NOT _xbb_prev_asset_mode STREQUAL _xbb_asset_mode)
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/assets")
    file(WRITE "${XBB_ASSET_MODE_STAMP}" "${_xbb_asset_mode}")
endif()

set(XBB_EMBED_COMMON_SCRIPT "${CMAKE_CURRENT_SOURCE_DIR}/scripts/embed_common.py")

include("${CMAKE_CURRENT_LIST_DIR}/font.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/mesh.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/sound.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/texture.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/animation.cmake")
