#pragma once

#include "raylib.h"

constexpr float DEMO_TOTAL_TIME = 8.0f;
constexpr double DOUBLE_CLICK_TIME = 0.3f;

constexpr float BLOB_STATIC_END_TIME = 0.6f;
constexpr float BLOB_ZERO_INTENSE_END_TIME = BLOB_STATIC_END_TIME + 0.5f;
constexpr float BLOB_BASE_INTENSITY = 0.3f;

constexpr float FINAL_HOLD_TIME = 2.0f;
constexpr float FINISH_TRANSITION_TIME = 0.8f;
constexpr float FINISH_START_TIME = DEMO_TOTAL_TIME - FINAL_HOLD_TIME - FINISH_TRANSITION_TIME;
constexpr float FINISH_STOP_TIME = DEMO_TOTAL_TIME - FINAL_HOLD_TIME;

constexpr float MAX_INTENSITY_TIME = FINISH_START_TIME;
constexpr float MAX_INTENSITY_DELTA = MAX_INTENSITY_TIME - BLOB_ZERO_INTENSE_END_TIME;
constexpr float OO_MAX_INTENSITY_DELTA = 1.0f / MAX_INTENSITY_DELTA;
constexpr float DEMO_START_INTENSITY = 0.0f;

constexpr float BLOB_PULSE_START = BLOB_STATIC_END_TIME;
constexpr float BLOB_PULSE_END = FINISH_STOP_TIME - 0.4f;
constexpr float BLOB_PULSE_ELAPSED = BLOB_PULSE_END - BLOB_PULSE_START;

constexpr float SCENE_ANIM_LEN = 4.5f;
constexpr float SCENE_ANIM_START_TIME = BLOB_STATIC_END_TIME + 0.25f;

constexpr float TEXT_ANIM_START_TIME = DEMO_TOTAL_TIME - FINAL_HOLD_TIME;
constexpr float TEXT_ANIM_LEN = 0.25f;
constexpr float SLASH_GRADIENT_TRANSITION_START = FINISH_START_TIME - 0.5f;
constexpr float SLASH_GRADIENT_TRANSITION_END = FINISH_STOP_TIME;
constexpr float SLASH_GRADIENT_TRANSITION_MUL = 1.0f / (SLASH_GRADIENT_TRANSITION_END - SLASH_GRADIENT_TRANSITION_START);

constexpr float GLOW_FADE_CIRCLE_START = (FINISH_START_TIME - 0.5f);
constexpr float GLOW_FADE_CIRCLE_MUL = (1.0f / 0.3f);
constexpr float GLOW_FADE_SCREEN_START = (GLOW_FADE_CIRCLE_START + 0.3f);
constexpr float GLOW_FADE_SCREEN_MUL = (1.0f / 0.25f);

#define XD_TEXT_TITLE CLITERAL(Color){ 190, 250, 94, 255 }
