string(REPLACE
    " -Xlinker /MANIFEST:EMBED"
    ""
    CMAKE_C_LINK_EXECUTABLE
    "${CMAKE_C_LINK_EXECUTABLE}"
)

string(REPLACE
    " -Xlinker /MANIFEST:EMBED"
    ""
    CMAKE_CXX_LINK_EXECUTABLE
    "${CMAKE_CXX_LINK_EXECUTABLE}"
)

string(REPLACE
    " -Xlinker /MANIFEST:EMBED"
    ""
    CMAKE_C_CREATE_SHARED_LIBRARY
    "${CMAKE_C_CREATE_SHARED_LIBRARY}"
)

string(REPLACE
    " -Xlinker /MANIFEST:EMBED"
    ""
    CMAKE_CXX_CREATE_SHARED_LIBRARY
    "${CMAKE_CXX_CREATE_SHARED_LIBRARY}"
)